hostAddress: 47.112.35.237

server:
  port: 7004

spring:
  dubbo:
    application:
      name: user-comsumer
    registry:
      address: zookeeper://${hostAddress}:2181
    scan: com.edu.scau.usercomsumer.controller