hostAddress: 47.112.35.237

server:
  port: 7002

spring:
  dubbo:
    application:
      name: order-consumer
    registry:
      address: zookeeper://${hostAddress}:2181
    scan: com.edu.scau.orderconsumer.controller