hostAddress: 47.112.35.237

server:
  port: 7012
spring:
  datasource:
    url: jdbc:mysql://${hostAddress}:3306/g-order?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  dubbo:
      application:
        name: notice-provicer
      registry:
        address: zookeeper://${hostAddress}:2181
      protocol:
        name: dubbo
        port: 20883
      scan: com.edu.scau.orderprovicer.serviceImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count
  page-size-zero: true
